config/routes.rb
FlywheelDotCom::Application.routes.draw do
  
  root :to => 'home#index'
  match '/about' => 'home#about'
  match '/fleet' => 'home#fleet'
  match '/faqs' => 'home#faqs'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
  end
  
  def faqs
  end

  def fleet
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.haml
%section#about
  %aside.span2
    %ul
      %li
        = link_to "News", "#"
      %li
        = link_to "Team", "#", class: "active"
      %li
        = link_to "Jobs", "#"
      %li
        = link_to "Contact", "#"
      
  %section.text_part.span6
    %h1
      How Flywheel 
      %br
      Got Rolling
    %p
      Flywheel was created as an innovative mobile solution to an age-old, |
      real-world problem. It's a reassurance to busy, city-driven people that an affordable |
      ride-on-the-fly is always just a smartphone tap away.
    %p
      The inspiration for Flywheel came from the universal experience of not being able to |
      get a cab at the most inopportune times. For our CEO, it was a washed out access road at JFK and a 10-mile |
      walk through Queens, NY in the rain unable to even tell a dispatcher where he was. For our chief |
      Product Officer, it was beginning taken for a ride(literally) through the streets of Bombay in a |
      gypsy cab with a rigged meter.
    %p
      They all had the same thought: "There has to be a better way"
      %span
        = link_to "Read more", "", class: "read_more"
    %article.sub_part
      %p
        We are not a disrupter-we are a catalyst for change. That's right, Flywheel plays by the rules. |
        We are hardwired into the meters of licensed taxis so you know exactly what you're paying. |
        No gimmicks. No games. Our cabs are regulated for passenger safety by teh cities in which they |
        operate, so our riders know they're in a safe vehicle with an accurate meter (as opposed to pricing based on imprecise GPS location).
      %p
        For cab drivers, Flywheel means greater efficiency and an affordable to expensive dispatch services. |
        For riders, Flywheel means that you will always have a ride waiting to get you from point A to point B(as well |
        as point C thru Z). For the future, Flywheel means that one day the universal cab experience may just be getting |
        a ride withease in every city around the world. Hey, we may even be the ride that gets you around the world (stay tuned).
      %p
        City life is tough. We're here to make it easier. Flywheel is the secret shortcut for your daily life. So |
        wher do you need a ride to today? fire up your Flywheel-we're ready to roll.
  .clear
  %section.image_part
    .span2
    = image_tag(asset_path("about_people.png"), class: "span7")

app/views/home/faqs.html.haml
%section#faqs.span12
  %section.text_part
    %h1.span10
      help hq
    %article.riders
      %a.span6.heading
        %h3
          flywheel for riders --- on your device
      %span.img
        %img{src: asset_path("contact_us_for_riders.png")}
      %section.content.span10
        %article
          %h4
            what is flywheel?
          %p
            Flywheel is a mobile app that enables you to hail a cab from your smartphone, |
            watch it approach, and pay for your ride directly from your phone. Flywheel exists |
            to keep cities and city-driven people moving that's just how we roll.
        %br
        %article
          %h4
            why should you use flywheel?
          %p
            Flywheel is driven by the needs of city-driven people. Our passion is to make your life easier. |
            Top 3 reasons, we think you should use Flywheel:
            %ul
              %li
                %p
                  Requesting a cab has never been easier. With Flywheel, you no longer need to hail a cab |
                  on the street or call the cab company.
                %p
                  You know exactly where your driver is, know when they will arrive, can chat directly with them.
                %p
                  You can pay conveniently directly from your smartphone.
        %br
        %article
          %h4
            where can you use flywheel?
          %p
            Flywheel's coverage is rapidly growing across the nation. We now have access to over 2,000 |
            cabs in the following locations:
            %p CA: Los Angeles, Santa Barbara, San Diego, San Francisco-Bay Area
            %p FL: Daytona Beach, Miami, Naples, Orlando
            %p GA: Atlanta
            %p KY: Louisville, Lexington
            %p MI: Lansing
            %p OH: Cleveland
            %p OK: Oklahoma City
            %p OR: Portland
            %p PA: Philadelphia
            %p TX: Dallas, San Antonio
            %br/
            Don't see your city? Don't worry; we are adding more cities every week.
        %br
        %article
          %h4
            Can You afford Flywheel?
          %p
            Flywheel is functional and affordable. You pay the cab’s standard meter rate at the end of your ride. |
            Flyhweel charges a low an introductory fee of $0.60 per ride when pay with the Flyhwheel app |
            on your smartphone.
            
        %br
        %article
          %h4
            Which smartphones are compatible with Flywheel?
          %p  
            Flywheel is currently available on the Android and iPhone. (hyperlink to related storefront)
        %br
        %article
          %h4
            What’s Flywheel’s cancellation policy?
          %p
            You can request a cab and then cancel for free within 2 minutes of the driver accepting your request |
            or if the driver arrives after the estimated pickup time. Don't worry we don't push 1st time offenders. |
            Otherwise there is a $6 cancellation fee.
          %p
            Trust us when the driver accepts your request, they commit both time and money to picking you up and |
            the only thing we ask is that you show up.
        %br
        %article
          %h4
            what are flywheel's rates?
          %p
            Flywheel prides itself on affordability, accountability and transparency. Fares are based on licensed |
            metered rates. Flywheel charges riders a very low 60-cent free per ride when payment is made through the |
            app. Riders can set tip amounts and/or percentages.
    
    .clear    
    %article.drivers
      %a.span6.heading
        %h3
          flywheel for drivers --- at your service
      %span.img
        %img{src: asset_path("contact_us_for_drivers.png")}
      .clear
      %section.content.span10
        %article
          %h4
            How do you sign up for Flywheel?
          %p
            We cannot sign up individual drivers for Flywheel, but we would love to speak to your |
            company about using our service. Please let your fleet manager know about your interest |
            and send us their contact information.
        %br
        %article
          %h4
            How do you get training or more info?
          %p
            We have comprehensive user guides for drivers, so please contact us at drivers@flywheel.com |
            or xxx-xxx-xxxx if you do not have one. We are happy to send you a copy and answer any of |
            your questions about how to use our driver device.
        %br
        %article
          %h4
            How much does it cost drivers?
          %p
            Flywheel is free for drivers! We do not charge a per ride fee and there are no clever, |
            hidden costs. The only thing you have to pay is a competitive credit card processing |
            rate on your mobile transactions - that's it.
        %br
        %article
          %h4
            How do you get paid?
          %p
            You get paid for your mobile transactions via direct deposit, check disbursement or through |
            your company. If you would like to sign up for direct payment, please contact us at |
            drivers@flywheel.com or xxx-xxx-xxxx. Direct deposit payments are processed the next business day!
        %br
        %article
          %h4
            What phone or device do I need?
          %p
            You will only need the driver device that is already in your vehicle. No other devices or |
            phones are required for drivers to use the Flywheel system and accept payments. 
        %br
        %article
          %h4
            Can you run swipe credit card payments through the Flywheel driver device?
          %p
            The driver device is capable of accepting swipe credit card payments through many popular |
            processing applications. Depending on your company's needs, this can be configured in unison |
            for all of the vehicles in your fleet.
        %br
        %article
          %h4
            How long do you have to accept a ride request?	
          %p
            This length of time is set by your company and can range from 5 seconds to 30 seconds. |
            Please check with your fleet manager to find out this time and let them know if you |
            feel it is inadequate.
        %br
        %article
          %h4
            What happens if you cancel a ride from a passenger?
          %p
            Once you accept a ride, you are obligated to pick up the passenger. Flywheel will be |
            monitoring driver performance and shifting hail priority for drivers who cancel |
            after accepting a ride. This is not a monetary penalty, but will prevent your from |
            receiving mobile hails for a designated period of time. 
        %br
        %article
          %h4
            Do you have to participate in mobile payments?
          %p
            You must participate in mobile payments in order to receive all of the benefits, |
            such as cancellation penalties, hails from passengers and direct deposit. |
            If you do not accept mobile payments, you will only be able to receive hails from your dispatcher.
        %br
        %article
          %h4
            what happens if a rider cancels a request or is a no-show?
          %p
            If a rider cancels or no-shows you, they will be charged a penalty and you will be paid $5. |
            The rules are:
            %ul
              %li
                Passengers have 2 minutes after you accept their order to change their ming. If they |
                cancel after 2 minutes, you get $5.
              %li
                Passenger have 3 minutes to reach you after you arrive on location. If you try to contact them, |
                wait 3 minutes and they are not outside, you get $5.
        %br
        %article
          %h4
            who can you contact if you have technical or account issues?
          %p
            You can always contact us at drivers@flywheelnow.com or our driver line at (888)667-7991 |
            with any questions or concerns. We look forward to hearing from you, and always appreciate your feedback |
            on any of our products.
    %article.question
      %a.span6.heading
        %h3
          have a question -- ask away
        
        

app/views/home/fleet.html.haml
%section#fleet
  %article.heading
    %h1.span8
      Flywheel for Fleets
    %span.span0.pull-right
      = image_tag(asset_path("sign_in.png"))
  %article.image
    = image_tag(asset_path("video.png"), class: "span12")
  %article.content_part
    %span
      = image_tag(asset_path("car.png"), class: "span6")
    %span.span5
      %h4
        sales info
      %p
        Flywheel partners with licensed fleets to deliver low cost, cloud based computerized dispatching |
        and mobile-hailing technology.
        
      .clear
      %ul
        %li
          Cut your systems cost--no software required, driver devices provided for every vehicle.
        %li
          Increase efficiency--location based auto-dispatching, access from any computer
        %li
          Increase visibility & passengers--receive mobile hails from Flywheel passenger app.
      .clear
      %p
        Flywheel only works with Fleets and their drivers.
      %br
      %p
        Find out more.
      = image_tag(asset_path("scheduled_a_demo.png"))
      %br
      %p
        Contact us: 
        %br
        650 260 1700
        %br
        Sales@flynow.com
      
      
        
        
        
      

app/views/home/index.html.haml
%aside.span6
  = image_tag(asset_path("mobiles.png"))
%section.text_part.span5
  %h2
    Your Ride is Here.
  %p
    There's one thing that all city people have in common. |
    We have places to go (and we need a ride). Movers and shakers, |
    hustlers and bustlers alike, we all need a cab. Like right now.
  %p
    Enter Flywheel:

  %ul
    %li
      %p
        Hall a cab right from your smartphone: we'll spot your location |
        and let you know when a driver is on the way.
    %li
      %p
        Call the driver from within the app for easy coordination.
    %li
      %p
        Track your cab as it comes to your pick-up location.
    %li
      %p
        Pay for your ride with the touch of a button: |
        no need to hunt for cash or a credit card.
  
  %p
    From San Francisco to Miami and everywhere in between:
    
  %p CA: San Diego, San Francisco Bay Area
  %p FL: Daytona Beach, Miami, Naples
  %p GA: Atlanta
  %p KY: Louisville, Lexington
  %p MI: Lansing
  %p OH: Cleveland
  %p OK: Oklahoma City
  %p TX: Dallas, San Antonio
  
  %p
    Your ride is waiting for you.
  
  %h3
    Download the free app now!
    
  .span2.ios
    = image_tag(asset_path("ios.png")) 
  .span2.android
    = image_tag(asset_path("android.png")) 
    

app/views/layouts/_nav.html.haml
%ul
  %li
    %a{href: about_path, class: "#{'current' if controller.controller_name == 'home' && controller.action_name == 'about'}"} About
  %li
    %a{href: fleet_path, class: "#{'current' if controller.controller_name == 'home' && controller.action_name == 'fleet'}"} Fleet
  %li
    %a{href: faqs_path, class: "#{'current' if controller.controller_name == 'home' && controller.action_name == 'faqs'}"} FAQs
.clearfix

app/views/layouts/application.html.haml
!!!
%html
%head
  %title
    FlywheelDotCom
  %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
  = stylesheet_link_tag "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags
%body
  %section#header.container-fluid
    %article#logo.span4
      = link_to(image_tag(asset_path("logo.png")), root_url)
    %nav.span3
      = render "layouts/nav"
  %section#content.container-fluid
    .span12
      = yield
  %section#footer
    .span4
      %p
        @ 2012 Flywheel software inc
    .span4.social
      .span0
        = image_tag(asset_path("facebook.png"))
      .span0
        = image_tag(asset_path("twitter.png"))